### PR TITLE
Missing dots

### PR DESCRIPTION
**Pull request by tejas456sawant**
Constants need to be - 
Roam.startTracking(Roam.TrackingMode.ACTIVE);
Roam.startTracking(Roam.TrackingMode.BALANCED);
Roam.startTracking(Roam.TrackingMode.PASSIVE);

### CODE REVIEW

**Review by manojadithya — COMMENTED** [review]
I'm sorry but that not correct. Have you tested the methods?

**Comment by tejas456sawant** [comment]
Yes, https://github.com/roam-ai/roam-reactnative/blob/master/js/index.ts#L11

image

**Comment by manojadithya** [comment]
Thanks for sharing this! 🔥

**Comment by jothipriyadharshanr** [comment]
Thanks @tejas456sawant for your contribution. We have updated the Readme.md with more clear content.

**Comment by tejas456sawant** [comment]
Hello,

I am adding roam.ai to my react native project, but it shows location hits
as 0.

[image: image.png]

Also, location listers are not printing anything and if I hit the insights
API, it shows the following response.

[image: image.png]

My Code -

import Roam from "roam-reactnative";


Roam.checkLocationPermission((status: any) => {
  if (status === "DENIED") {
    Roam.requestLocationPermission();
  }
});

Roam.checkLocationServices((status: any) => {
  if (status === "DENIED") {
    Roam.requestLocationServices();
  }
});

Roam.checkBackgroundLocationPermission((status: any) => {
  if (status === "DENIED") {
    Roam.requestBackgroundLocationPermission();
  }
});

Roam.startTracking("PASSIVE");

Roam.updateLocationWhenStationary(10);

Roam.allowMockLocation(true);

Roam.createUser(
  "TEST_USER",
  (success: any) => {
    console.log("User created: ", success);
  },
  (error: any) => {
    console.log("User creation error: ", error);
  },
);

Roam.startListener("location", (location) => {
  console.log("Location", location);
});

**Comment by manojadithya** [comment]
Looping JOE

**Pull request closed without merging**
